version: "3.7"

services:
  xtlab-mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sqlserver-xtlab
    restart: always
    hostname: mssql
    environment:
      SA_PASSWORD: 123456tdung
      ACCEPT_EULA: 'Y'
      trustServerCertificate: "true" # Thêm dòng này để bật chế độ trust server certificate
    volumes:
      - mssqlvolume:/var/opt/mssql/data
    ports:
      - "1433:1433"

volumes:
  mssqlvolume:
    name: sqlserver-xtlab-vl
