// <auto-generated />
using DAFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAFramework.Migrations
{
    [DbContext(typeof(MyWebContext))]
    partial class MyWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAFramework.Models.PlanetModel", b =>
                {
                    b.Property<int>("id_planet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_planet"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("name_planet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("id_planet");

                    b.ToTable("planets");
                });
#pragma warning restore 612, 618
        }
    }
}
